### ISSUE TITLE
Header background doesn't fill width at certain resolutions

### ISSUE THREAD

**Issue by zapplecat** [Manotomo-Alliance-Support-Squad/WWS#26]
![image](https://user-images.githubusercontent.com/6146988/112425417-051b6880-8d04-11eb-9e25-a92043f81738.png)

**Comment by R-Jim** [comment]
![image](https://user-images.githubusercontent.com/30451707/119502067-b8035380-bd93-11eb-8f17-f427c24c59bf.png)
The header was affected by this rule. And when you change the width: height ratio, then background will try to stretch to fit it which cause the bug

**Comment by R-Jim** [comment]
This as well
![image](https://user-images.githubusercontent.com/30451707/119503597-59d77000-bd95-11eb-84c0-b7832405fa4a.png)

**Comment by zapplecat** [comment]
> This as well
> ![image](https://user-images.githubusercontent.com/30451707/119503597-59d77000-bd95-11eb-84c0-b7832405fa4a.png)

This was intentional for mobile since the other option didn't look quite as good.
